// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Musica_SucapucaRodrigo.Models;

[Table("Track")]
[Index("AlbumId", Name = "IFK_TrackAlbumId")]
[Index("GenreId", Name = "IFK_TrackGenreId")]
[Index("MediaTypeId", Name = "IFK_TrackMediaTypeId")]
public partial class Track
{
    [Key]
    [DisplayName()]
    public int TrackId { get; set; }

    [Required]
    [StringLength(200)]
    [DisplayName("Nombre")]
    public string Name { get; set; }

    [DisplayName("Album Id")]
    public int? AlbumId { get; set; }

    [DisplayName("Id de Tipo de medio")]
    public int MediaTypeId { get; set; }

    [DisplayName("Id Genero")]
    public int? GenreId { get; set; }

    [StringLength(220)]
    [DisplayName("Compositor")]
    public string Composer { get; set; }

    [DisplayName("Milisegundos")]
    public int Milliseconds { get; set; }

    [DisplayName("Bytes")]
    public int? Bytes { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    [DisplayName("Precio Unidad")]
    public decimal UnitPrice { get; set; }

    [ForeignKey("AlbumId")]
    [InverseProperty("Tracks")]
    public virtual Album Album { get; set; }
}