// <auto-generated />
using AnimalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalApp.Migrations
{
    [DbContext(typeof(AnimalAppContext))]
    [Migration("20231016220145_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnimalApp.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPropietario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idPropietario");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Es un gato de color negro y blanco",
                            Name = "Fitipanlis",
                            idPropietario = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Es un crocodilo muy grande",
                            Name = "Renekton",
                            idPropietario = 2
                        });
                });

            modelBuilder.Entity("AnimalApp.Models.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Propietario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jhenny",
                            Number = "666 666 666",
                            Surname = "Alaca"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rodrigo",
                            Number = "666 666 666",
                            Surname = "Sucapuca Alaca"
                        });
                });

            modelBuilder.Entity("AnimalApp.Models.Animal", b =>
                {
                    b.HasOne("AnimalApp.Models.Propietario", "propietario")
                        .WithMany("Animales")
                        .HasForeignKey("idPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("propietario");
                });

            modelBuilder.Entity("AnimalApp.Models.Propietario", b =>
                {
                    b.Navigation("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
