// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using seguridad5.Models;
using seguridad5.Seeder;

namespace seguridad5.Data;

public partial class DiccionarioContext : IdentityDbContext
{
    public DiccionarioContext()
    {
    }

    public DiccionarioContext(DbContextOptions<DiccionarioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Espeng> Espengs { get; set; }
     
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Espeng>().ToTable("Espeng",table=>table.ExcludeFromMigrations());
        modelBuilder.Entity<Frase>().ToTable("Frase",table=>table.ExcludeFromMigrations());

        modelBuilder.Entity<Espeng>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Espeng__3213E83F847D94E2");
        });

        //SEEDER 
        var seeder = new Seeder.Seeding();
        seeder.SeedData(modelBuilder);

        //OnModelCreatingPartial(modelBuilder);
        base.OnModelCreating(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}